# This is the main configuration file for PolymartBase
# Change the values accordingly to your server

# Polymart API base url
# The bot won't work if this is incorrect
base-url: "https://api.polymart.org"

# Your Discord bot token
bot-token: "TOKEN"

# Your Discord server ID
server-id: 0000000

# Global Polymart API Key
# Used to fetch user name and user ID
global-api-key: "API KEY HERE"

# Your service name
# Can be whatever you want
service: "ExampleService"

# Bot activity
# Will be shown as Playing <activity>
# Leave empty to disable
activity: "Change me"

# Specify this if you want the /verify command to only be able to used in a specific channel
# Discord channel ID, leave this empty to disable
channel-id: 0000

# Display user avatar on verification summary
display-user-avatar: true

# Emoji indicators, will be used in anything
# For built in emojis, use standard name (i.e. :smile:)
# For external emojis, use emoji ID
# To get the ID of the emoji, type \ before the emoji
indicator:
  true: ":white_check_mark:"
  false: ":x:"

# Roles ID that will be allowed to use reload command
reload-role-ids:
  - 0000
  - 0000

# Useful for debugging
debug:
  # Print verbose log to the bot's console
  # It will print all of bot activitiies like api calls and just internal stuff
  # Your console might get spammed, but its useful to see what's happening behind the scene
  verbose: false