# This is the main configuration file for PolymartBase
# Change the values accordingly to your server

# WHEN CREATING THE BOT THOUGH DISCORD DEVELOPER PORTAL
# MAKE SURE TO ENABLE "bot" AND "application.commands" SCOPE
# OTHERWISE THE BOT WON'T WORK

# PolymartBase have a few info placeholders for bot version, date, etc
# You can use these placeholders the layout customization

# %version%: Bot version (i.e. 3.2.3)
# %branch%: Bot branch (i.e. oss/main)
# %date%: Current date (format: m/d/y h:m)
# %user_name%: Username (i.e. John)
# %user_discriminator%: Discriminator of an user (i.e. 9999)
# %user_full%: Full username and discriminator (i.e. John#9999)

# Polymart API base url
# The bot won't work if this is incorrect
base-url: "https://api.polymart.org"

# Your Discord bot token
bot-token: "TOKEN"

# Your Discord server ID
server-id: 0000000

# Global Polymart API Key
# Used to fetch user name and user ID
global-api-key: "API KEY HERE"

# Your service name
# Can be whatever you want
service: "ExampleService"

# Bot activity
# Will be shown as Playing <activity>
# Leave empty to disable
activity: "Change me"

# Specify this if you want the /verify command to only be able to used in a specific channel
# Discord channel ID, leave this empty to disable
channel-id: 0000

# Emoji indicators, will be used in anything
# For built in emojis, use standard name (i.e. :smile:)
# For external emojis, use emoji ID
# To get the ID of the emoji, type \ before the emoji
indicator:
  # Workaround a funny "bug"?
  check_mark: ":white_check_mark:"
  x: ":x:"

# Layout settings
layout:
  # Layout mode for verification summary
  # There are 2 modes that you can choose from: default & new
  # "default" mode is the standard layout currently used in all versions of the bot
  # "new" mode is the newer layout available from 3.2.3, contain more information and a better layout
  # The "default" layout won't get any further improvements
  mode: "default"
  # Display user avatar on verification summary
  display-user-avatar: true
  # Layout title
  # Verification summary only
  title: "Verification Summary for User %user_full%"
  # Layout footer
  # Used globally
  footer: "Requested by %user_full% at %date% | Bot version %version% (%branch%)"