# This is the main configuration file for PolymartBase
# Change the values accordingly.

# Polymart API base url
# You most likely don't want to change this.
base_url: "https://api.polymart.org"

# Your Discord bot token
bot_token: "DISCORD_BOT_TOKEN"

# Your Discord server ID
server_id: 00000000000000

# Global Polymart API Key
# Used globally for fetching user information and when there's no resource-specific API key.
global_api_key: "API_KEY_HERE"

# Your service name
# Can be whatever you want.
service: "MyBot"

# Bot activity
# Will be shown as Playing <activity>.
# Leave empty to disable.
activity: "Change me!"

# Limit the usage of the /verify command to a list of specified channels.
# Leave empty to disable.
channel_id: 
  - 0000

# Default indicators
# For built-in emojis, write it the same way you did when texting (e.g. :smile:)
# For external emojis, insert "\" before the emoji name to get its ID (e.g. "\:thonk:")
indicator:
  check_mark: ":white_check_mark:"
  x: ":x:"

# Layout customization (not much actually).
layout:
  # The color of error embeds (hex color).
  error_color: "b33825"
  # The color of the summary embeds (hex color).
  summary_color: "13ad75"
  
# Disable the bot built-in failsafe.
# Doing this will make the bot ignore all the built-in error checks, making it more error-prone.
# Please do not disable this unless you know what you are doing.
disable_failsafe: false