# This is the main configuration file for PolymartBase
# Change the values accordingly to your server

# Polymart API base url
# The bot won't work if this is incorrect
base-url: "https://api.polymart.org"

# Your Discord bot token
bot-token: "TOKEN"

# Your Discord server ID
server-id: 0000000

# Global Polymart API Key
# Used to fetch user name and user ID
global-api-key: "API KEY HERE"

# Your service name
# Can be whatever you want
service: "ExampleService"

# Bot activity
# Will be shown as Playing <activity>
activity: "You probably want to change this"

# Specify this if you want the /verify command to only be able to used in a specific channel
# Discord channel ID, leave this empty to disable
channel-id: 0000

# Commands
# Set role restrictions for commands
commands:
  # The main command of the bot
  # You don't want to restrict this command unless you want to fix it internally
  verify:
    # Restrict or not
    restrict: false
    # Roles ID that are allowed to use this command
    # Other roles will be blocked
    roles:
      - 0000
  # Reload config.yml file
  # resources.yml will be reloaded everytime someone run /verify
  # Syntax is the same as above
  reload:
    restrict: false
    roles:
      - 0000

# Useful for debugging or moderation purpose
debug:
  # Print verbose log to the bot's console
  # It will print all API calls, as well as the result, and all bot activity and internal
  # Your console might get spammed, but its useful to see what's happening behind the scenes
  verbose: false
  # Log all bot activities to a Discord channel
  logging:
    # Enable logging?
    enabled: false
    # Channel ID to send the log message
    # Will be ignored if enabled is set to false
    channel-id: 0000